name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: 
        docker build . --file dockerfile -t heba/jenkins_lab3:v1.10
        docker login -u ${{secrets.DOCKER_USERNAME}} -P {{secrets.DOCKER_PASSWORD}}
        docker push heba/jenkins_lab3:v1.10
      
