name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: 
        docker build . --file dockerfile --tag hebaadel/jenkins_lab3:v1.10
        docker login -u ${{secrets.DOCKER_USERNAME}} -p {{secrets.DOCKER_PASSWORD}}
        docker push hebaadel/jenkins_lab3:v1.10
      
